export const Investments = [
  {
    name: ' 1. Ishare Global Property Secs Eq Index Fund Class H Inc',
    id: '1',
    value: '1000',
    units: '100',
    assetType: '1',
    assetSubType: '1',
    fundAssetType: '1',
  },
  {
    name: ' 2.0000 Ishare Global Property Secs Eq Index Fund Class H Inc ',
    id: '2',
    value: '1000',
    units: '100',
    assetType: '2',
    assetSubType: '2',
    fundAssetType: '2',
  },
  {
    name: ' 3. Ishare Global Property Secs Eq Index Fund Class H Inc',
    id: '3',
    value: '1000',
    units: '100',
    assetType: '3',
    assetSubType: '3',
    fundAssetType: '3',
  },
  {
    name: ' 4. Ishare Global Property Secs Eq Index Fund Class H Inc',
    id: '4',
    value: '1000',
    units: '100',
    assetType: '4',
    assetSubType: '4',
    fundAssetType: '4',
  },
  {
    name: ' 5. Ishare Global Property Secs Eq Index Fund Class H Inc',
    id: '5',
    value: '1000',
    units: '100',
    assetType: '5',
    assetSubType: '5',
    fundAssetType: '5',
  },
];
